=== Nestorbd/BIU/UT01/Tarea/XSD/Ejemplo2.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Autor">
    <xs:annotation>
      <xs:documentation>Escribe un documento XML bien formado para representar el índice de
        contenidos de la entrada en Wikipedia sobre el escritor español de la generación del 27
        Pedro Salinas</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Nombre" />
        <xs:element name="Indice">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Elemento" type="element" maxOccurs="unbounded" minOccurs="0">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="element">
    <xs:sequence>
      <xs:element type="xs:string" name="Subelemento" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" />
  </xs:complexType>
</xs:schema>

=== Nestorbd/BIU/UT01/Tarea/XSD/Ejemplo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Autor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejemplo2.xsd">
    <Nombre>Pedro Salinas</Nombre>
    <Indice>
      <Elemento name="Biografía">
        <Subelemento>Primeros años</Subelemento>
        <Subelemento>Matrimonio y cátedra</Subelemento>
        <Subelemento>Romance</Subelemento>
        <Subelemento>Guerra Civil y exilio</Subelemento>
      </Elemento>
      <Elemento name="Poeta del 27">
        <Subelemento>Etapas poéticas</Subelemento>
        <Subelemento>Poeta del amor</Subelemento>
      </Elemento>
      <Elemento name="Prosista"></Elemento>
      <Elemento name="Dramaturgo"></Elemento>
      <Elemento name="Obra">
        <Subelemento>Poesía</Subelemento>
        <Subelemento>Teatro</Subelemento>
        <Subelemento>Traducciones</Subelemento>
        <Subelemento>Narrativa</Subelemento>
        <Subelemento>Ensayo</Subelemento>
        <Subelemento>Epistolario</Subelemento>
      </Elemento>
      <Elemento name="Referencias"></Elemento>
      <Elemento name="Notas"></Elemento>
      <Elemento name="Bibliografía"></Elemento>
    </Indice>
  </Autor>
